// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.subsystems;

import com.ctre.phoenix6.swerve.SwerveRequest;
import com.limelightvision.Limelight;
import frc.robot.generated.TunerConstants;
import frc.robot.utils.Telemetry;
import java.util.function.Supplier;
import org.wpilib.command3.Command;
import org.wpilib.command3.Mechanism;
import org.wpilib.command3.Scheduler;
import org.wpilib.math.geometry.Pose2d;
import org.wpilib.math.kinematics.ChassisVelocities;
import org.wpilib.math.linalg.Matrix;
import org.wpilib.math.numbers.N1;
import org.wpilib.math.numbers.N3;

/**
 * Command-based wrapper around {@link CommandSwerveDrivetrain}. The drivetrain already extends the
 * Tuner-generated class, so it can't also be a {@code Mechanism} (which is a class in Commands v3);
 * this owns the drivetrain instead and exposes the drive commands.
 */
public class DriveMechanism extends Mechanism {
  // CTRE-recommended construction: TunerConstants is generated by Tuner X and createDrivetrain()
  // is its factory. Keep this verbatim and regenerate TunerConstants from Tuner X for your robot
  // (the checked-in one is an EXAMPLE placeholder with fake device IDs/gains).
  private final CommandSwerveDrivetrain drivetrain = TunerConstants.createDrivetrain();

  // Publishes the drivetrain state to NetworkTables (and thus the WPILOG via DataLogManager). This
  // is the project's logging surface - see Telemetry and the log-reading skill.
  private final Telemetry telemetry = new Telemetry();

  public DriveMechanism() {
    super("Drivetrain");
    // The drivetrain's perspective update used to live in periodic(); run it every loop.
    Scheduler.getDefault().addPeriodic(drivetrain::applyOperatorPerspective);
    // CTRE calls this from the odometry thread (250 Hz on FD): publish telemetry, and feed every
    // Limelight the freshest heading + yaw rate (degrees, CCW+) for MegaTag2.
    drivetrain.registerTelemetry(
        state -> {
          telemetry.telemeterize(state);
          Limelight.setSharedRobotOrientation(
              state.Pose.getRotation().getDegrees(),
              Math.toDegrees(state.Velocity.omega),
              0,
              0,
              0,
              0);
        });
  }

  /** Returns a command that continuously applies the supplied control request to the drivetrain. */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return runRepeatedly(() -> drivetrain.setControl(request.get())).named("applyRequest");
  }

  /** Resets the field-centric heading so "forward" matches the driver's current facing. */
  public Command seedFieldCentric() {
    return run(coroutine -> {
          drivetrain.seedFieldCentric();
        })
        .named("seedFieldCentric");
  }

  /**
   * Applies a swerve control request to the underlying drivetrain. Exposed so a command that
   * already requires this mechanism (e.g. {@code DriveToTag}) can drive it without needing direct
   * access to the Phoenix swerve object.
   */
  public void setControl(SwerveRequest request) {
    drivetrain.setControl(request);
  }

  /**
   * The robot's current field pose from odometry, in the blue-alliance-origin field frame (the
   * Phoenix convention - the origin does not flip with alliance). Used by pose-following commands
   * such as {@code DriveToPose} for feedback.
   */
  public Pose2d getPose() {
    return drivetrain.getState().Pose;
  }

  /**
   * The robot's current field-relative velocity from odometry. The drivetrain reports a
   * robot-centric velocity; this rotates it into the field frame so it can seed a field-relative
   * profile (e.g. {@code LinearPath}).
   */
  public ChassisVelocities getFieldVelocity() {
    var state = drivetrain.getState();
    return state.Velocity.toFieldRelative(state.Pose.getRotation());
  }

  /**
   * Fuses a vision pose estimate into the drivetrain's Kalman filter. Exposed so the {@link
   * frc.robot.subsystems.vision.Vision} pose feeder can correct odometry without direct access to
   * the Phoenix swerve object.
   *
   * <p><b>Timebase:</b> Phoenix shares the WPILib timebase in the 2027 line (it dropped {@code
   * Utils.fpgaToCurrentTime}), and LimelightLib stamps estimates in that same timebase, so {@code
   * PoseEstimate.timestampSeconds} passes straight through - no conversion.
   *
   * @param visionRobotPose the robot pose measured by vision, blue-alliance-origin
   * @param timestampSeconds measurement timestamp in the WPILib timebase
   * @param stdDevs measurement standard deviations [x, y, theta]ᵀ (meters, radians)
   */
  public void addVisionMeasurement(
      Pose2d visionRobotPose, double timestampSeconds, Matrix<N3, N1> stdDevs) {
    drivetrain.addVisionMeasurement(visionRobotPose, timestampSeconds, stdDevs);
  }
}
