// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.subsystems;

import com.ctre.phoenix6.swerve.SwerveRequest;
import frc.robot.generated.TunerConstants;
import frc.robot.hardware.LoggedSwerveDrivetrain;
import frc.robot.utils.RunMode;
import java.util.function.Supplier;
import org.wpilib.command3.Command;
import org.wpilib.command3.Mechanism;
import org.wpilib.command3.Scheduler;
import org.wpilib.math.geometry.Pose2d;
import org.wpilib.math.kinematics.ChassisVelocities;
import org.wpilib.math.linalg.Matrix;
import org.wpilib.math.numbers.N1;
import org.wpilib.math.numbers.N3;

/**
 * Command-based wrapper around {@link CommandSwerveDrivetrain}, which can't be a {@code Mechanism}
 * itself (it already extends the Tuner-generated class). Owns the drivetrain and exposes the drive
 * commands.
 */
public class DriveMechanism extends Mechanism {
  // TunerConstants is generated by Tuner X. The checked-in one is an EXAMPLE with fake device
  // IDs/gains - regenerate it for your robot.
  private final CommandSwerveDrivetrain drivetrain = TunerConstants.createDrivetrain();

  // Routes the drivetrain state through the log so everything downstream replays.
  private final LoggedSwerveDrivetrain logged = new LoggedSwerveDrivetrain(drivetrain);

  public DriveMechanism() {
    super("Drivetrain");
    Scheduler.getDefault().addPeriodic(drivetrain::applyOperatorPerspective);
  }

  /** Returns a command that continuously applies the supplied control request to the drivetrain. */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return runRepeatedly(() -> setControl(request.get())).named("applyRequest");
  }

  /** Applies a swerve request directly - for commands that already require this mechanism. */
  public void setControl(SwerveRequest request) {
    if (RunMode.current() == RunMode.REPLAY) {
      return;
    }
    drivetrain.setControl(request);
  }

  /** The robot's field pose from odometry, blue-origin (the origin never flips with alliance). */
  public Pose2d getPose() {
    return logged.getPose();
  }

  /** The robot's field-relative velocity from odometry (rotated out of the robot frame). */
  public ChassisVelocities getFieldVelocity() {
    return logged.getFieldVelocity();
  }

  /**
   * Fuses a vision pose estimate into the pose estimator (used by {@link
   * frc.robot.subsystems.vision.Vision}). Phoenix and LimelightLib share the WPILib timebase in
   * 2027, so the timestamp passes straight through.
   *
   * @param visionRobotPose robot pose from vision, blue-origin
   * @param timestampSeconds timestamp in the WPILib timebase
   * @param stdDevs trust numbers [x, y, theta] (meters, radians) - smaller = trust vision more
   */
  public void addVisionMeasurement(
      Pose2d visionRobotPose, double timestampSeconds, Matrix<N3, N1> stdDevs) {
    if (RunMode.current() == RunMode.REPLAY) {
      return; // the pose comes from the log; there is no estimator running to correct
    }
    drivetrain.addVisionMeasurement(visionRobotPose, timestampSeconds, stdDevs);
  }
}
